spring.application.name=controle-de-ofs
springdoc.swagger-ui.path=/documentacao
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://localhost:3306/ordensof
spring.datasource.username=superColaborador
spring.datasource.password=senha123!